import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./_providers";
import { Session } from "next-auth";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  x: Readonly<{
    children: React.ReactNode;
    session: Session;
  }>,
) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={x.session}>{x.children}</Providers>
      </body>
    </html>
  );
}
